# Generated by Django 4.2.2 on 2023-06-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=666)),
                ('link', models.CharField(max_length=666)),
                ('shortlink', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=666)),
                ('rating', models.IntegerField()),
                ('logo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.logos')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channels')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
