# Generated by Django 4.2.2 on 2023-06-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.users')),
                ('chat_id', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=140, null=True)),
                ('firstname', models.CharField(max_length=140, null=True)),
                ('lastname', models.CharField(max_length=140, null=True)),
                ('email', models.EmailField(max_length=140, null=True)),
                ('want_recomend', models.BooleanField(null=True)),
                ('rating', models.IntegerField(null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.countries')),
                ('language_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.languages')),
            ],
        ),
    ]
