# Generated by Django 4.2.2 on 2023-06-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0003_alter_userdetail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chat_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.countries'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.languages'),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='want_recomend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
