# Generated by Django 4.2.2 on 2023-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='chat_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
