# Generated by Django 4.2.2 on 2023-06-19 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
