# Generated by Django 4.2.2 on 2023-06-19 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
