# Generated by Django 4.2.2 on 2023-06-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_date_change_alter_users_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
